<?php

namespace Blog\BlogBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\From;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function buildWithAlias($alias)
    {
        return $this->getEntityManager()->createQueryBuilder($alias);
    }

    public function getThreeLast()
    {
        return $this->buildWithAlias('p')
            ->select('p.title','p.content','p.createdAt','p.updatedAt')
            ->from('BlogBundle:Post','p')
            ->setMaxResults(3)
            ->orderBy('p.createdAt','DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function getThreeFirst()
    {
        return $this->buildWithAlias('p')
            ->select('p.title','p.content','p.createdAt','p.updatedAt')
            ->from('BlogBundle:Post','p')
            ->setMaxResults(3)
            ->orderBy('p.createdAt','ASC')
            ->getQuery()
            ->getResult()
        ;
    }
}
